-- =============================================================================
-- Attendance V2 - database changes (UP)
-- Release date : 2026-09-28
-- Target       : MySQL 8.x, InnoDB, utf8mb4 (default schema of the xDesk app)
--
-- Equivalent to the Django migrations
--     platform_access.0014_seed_attendance_v2_capabilities
--     attendance_v2_access.0001_initial
-- Prefer:  python manage.py migrate attendance_v2_access
-- (do NOT run a plain `migrate`: other apps have unrelated pending migrations).
-- Use this script only where migrations are applied by hand, then run
-- section 4 so Django knows the migrations are already applied.
--
-- ALTERs on EXISTING tables: NONE.
-- Every ALTER TABLE below targets a NEW attv2_* table (foreign keys / columns
-- added after the referenced table exists). Legacy attendance tables
-- (daily_attendance, wfh_requests, holidays, leaves, eSSL `Att` in MSSQL)
-- are not modified.
--
-- New tables (14): attv2_location, attv2_device, attv2_collector,
--   attv2_collector_devices, attv2_sync_log, attv2_raw_punch, attv2_event,
--   attv2_shift, attv2_shift_schedule, attv2_shift_assignment,
--   attv2_daily_attendance, attv2_session, attv2_settings, attv2_audit_log
--
-- Referenced existing tables (must exist, InnoDB, INT id):
--   auth_user, platform_company, platform_branch, platform_capability,
--   platform_role, platform_role_capabilities, django_migrations
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. New tables, constraints and indexes (generated by `sqlmigrate`)
-- -----------------------------------------------------------------------------
--
-- Create model AttendanceDevice
--
CREATE TABLE `attv2_device` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(150) NOT NULL, `code` varchar(50) NOT NULL, `device_type` varchar(20) NOT NULL, `serial_number` varchar(100) NULL, `ip_address` char(39) NULL, `requires_wfh_approval` bool NOT NULL, `is_active` bool NOT NULL, `created_by` integer NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `company_id` integer NOT NULL);
--
-- Create model AttendanceCollector
--
CREATE TABLE `attv2_collector` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `collector_id` varchar(64) NOT NULL UNIQUE, `name` varchar(150) NOT NULL, `collector_type` varchar(20) NOT NULL, `api_key_hash` varchar(64) NOT NULL, `api_key_prefix` varchar(12) NOT NULL, `key_rotated_at` datetime(6) NULL, `version` varchar(50) NULL, `reported_status` varchar(20) NOT NULL, `last_seen_at` datetime(6) NULL, `last_sync_at` datetime(6) NULL, `last_success_at` datetime(6) NULL, `last_error_at` datetime(6) NULL, `last_error` varchar(500) NULL, `last_ip` char(39) NULL, `is_active` bool NOT NULL, `created_by` integer NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `company_id` integer NOT NULL);
CREATE TABLE `attv2_collector_devices` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `attendancecollector_id` integer NOT NULL, `attendancedevice_id` integer NOT NULL);
--
-- Create model AttendanceLocation
--
CREATE TABLE `attv2_location` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(150) NOT NULL, `code` varchar(50) NOT NULL, `location_type` varchar(20) NOT NULL, `is_active` bool NOT NULL, `created_by` integer NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `branch_id` integer NULL, `company_id` integer NOT NULL, `parent_id` integer NULL);
--
-- Add field location to attendancedevice
--
ALTER TABLE `attv2_device` ADD COLUMN `location_id` integer NULL , ADD CONSTRAINT `attv2_device_location_id_d75b7773_fk_attv2_location_id` FOREIGN KEY (`location_id`) REFERENCES `attv2_location`(`id`);
--
-- Create model AttendanceRawPunch
--
CREATE TABLE `attv2_raw_punch` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `external_employee_id` varchar(64) NOT NULL, `external_punch_id` varchar(128) NOT NULL, `punch_time` datetime(6) NOT NULL, `raw_punch_type` varchar(32) NULL, `punch_type` varchar(12) NOT NULL, `source` varchar(20) NOT NULL, `raw_data` json NULL, `received_at` datetime(6) NOT NULL, `status` varchar(24) NOT NULL, `error_message` varchar(500) NULL, `processed_at` datetime(6) NULL, `collector_id` integer NULL, `company_id` integer NOT NULL, `device_id` integer NOT NULL, `employee_id` integer NULL, `location_id` integer NULL);
--
-- Create model AttendanceEvent
--
CREATE TABLE `attv2_event` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `event_time` datetime(6) NOT NULL, `event_type` varchar(12) NOT NULL, `attendance_date` date NULL, `source` varchar(20) NOT NULL, `is_manual` bool NOT NULL, `manual_reason` varchar(500) NULL, `status` varchar(10) NOT NULL, `void_reason` varchar(500) NULL, `voided_by` integer NULL, `voided_at` datetime(6) NULL, `created_by` integer NULL, `created_at` datetime(6) NOT NULL, `company_id` integer NOT NULL, `device_id` integer NULL, `employee_id` integer NOT NULL, `location_id` integer NULL, `raw_punch_id` integer NULL UNIQUE);
--
-- Create model AttendanceSettings
--
CREATE TABLE `attv2_settings` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `duplicate_punch_window_minutes` integer UNSIGNED NOT NULL CHECK (`duplicate_punch_window_minutes` >= 0), `unspecified_punch_mode` varchar(20) NOT NULL, `collector_offline_after_minutes` integer UNSIGNED NOT NULL CHECK (`collector_offline_after_minutes` >= 0), `use_holiday_calendar` bool NOT NULL, `use_leave_records` bool NOT NULL, `updated_by` integer NULL, `updated_at` datetime(6) NOT NULL, `company_id` integer NOT NULL UNIQUE);
--
-- Create model AttendanceShift
--
CREATE TABLE `attv2_shift` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `code` varchar(30) NOT NULL, `description` varchar(500) NULL, `start_time` time(6) NOT NULL, `end_time` time(6) NOT NULL, `expected_work_minutes` integer UNSIGNED NOT NULL CHECK (`expected_work_minutes` >= 0), `grace_in_minutes` integer UNSIGNED NOT NULL CHECK (`grace_in_minutes` >= 0), `grace_out_minutes` integer UNSIGNED NOT NULL CHECK (`grace_out_minutes` >= 0), `break_minutes` integer UNSIGNED NOT NULL CHECK (`break_minutes` >= 0), `break_start` time(6) NULL, `break_end` time(6) NULL, `is_flexible` bool NOT NULL, `min_present_minutes` integer UNSIGNED NULL CHECK (`min_present_minutes` >= 0), `half_day_minutes` integer UNSIGNED NULL CHECK (`half_day_minutes` >= 0), `overtime_enabled` bool NOT NULL, `overtime_basis` varchar(20) NOT NULL, `min_overtime_minutes` integer UNSIGNED NOT NULL CHECK (`min_overtime_minutes` >= 0), `checkin_window_before_minutes` integer UNSIGNED NOT NULL CHECK (`checkin_window_before_minutes` >= 0), `checkout_window_after_minutes` integer UNSIGNED NOT NULL CHECK (`checkout_window_after_minutes` >= 0), `is_active` bool NOT NULL, `created_by` integer NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `company_id` integer NOT NULL);
--
-- Create model AttendanceShiftAssignment
--
CREATE TABLE `attv2_shift_assignment` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `scope` varchar(20) NOT NULL, `effective_from` date NOT NULL, `effective_to` date NULL, `is_active` bool NOT NULL, `remarks` varchar(500) NULL, `created_by` integer NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `branch_id` integer NULL, `company_id` integer NOT NULL, `employee_id` integer NULL, `shift_id` integer NOT NULL, `team_lead_id` integer NULL);
--
-- Create model AttendanceShiftSchedule
--
CREATE TABLE `attv2_shift_schedule` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `weekday` smallint UNSIGNED NOT NULL CHECK (`weekday` >= 0), `is_working_day` bool NOT NULL, `start_time` time(6) NULL, `end_time` time(6) NULL, `expected_work_minutes` integer UNSIGNED NULL CHECK (`expected_work_minutes` >= 0), `shift_id` integer NOT NULL);
--
-- Create model AttendanceSyncLog
--
CREATE TABLE `attv2_sync_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `kind` varchar(20) NOT NULL, `request_id` varchar(64) NOT NULL, `remote_ip` char(39) NULL, `status` varchar(20) NOT NULL, `received_count` integer NOT NULL, `accepted_count` integer NOT NULL, `duplicate_count` integer NOT NULL, `failed_count` integer NOT NULL, `errors` json NULL, `message` varchar(500) NULL, `started_at` datetime(6) NOT NULL, `finished_at` datetime(6) NULL, `collector_id` integer NULL, `company_id` integer NULL, `device_id` integer NULL);
--
-- Add field sync_log to attendancerawpunch
--
ALTER TABLE `attv2_raw_punch` ADD COLUMN `sync_log_id` integer NULL , ADD CONSTRAINT `attv2_raw_punch_sync_log_id_15e03d96_fk_attv2_sync_log_id` FOREIGN KEY (`sync_log_id`) REFERENCES `attv2_sync_log`(`id`);
--
-- Create model EmployeeDailyAttendance
--
CREATE TABLE `attv2_daily_attendance` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `attendance_date` date NOT NULL, `shift_snapshot` json NULL, `day_type` varchar(20) NOT NULL, `leave_portion` varchar(10) NOT NULL, `status` varchar(20) NOT NULL, `first_in` datetime(6) NULL, `last_out` datetime(6) NULL, `total_work_minutes` integer NOT NULL, `total_break_minutes` integer NOT NULL, `expected_work_minutes` integer NOT NULL, `late_minutes` integer NOT NULL, `early_departure_minutes` integer NOT NULL, `overtime_minutes` integer NOT NULL, `is_late` bool NOT NULL, `is_early_departure` bool NOT NULL, `session_count` integer NOT NULL, `has_missing_punch` bool NOT NULL, `remarks` varchar(500) NULL, `processed_at` datetime(6) NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `company_id` integer NOT NULL, `employee_id` integer NOT NULL, `first_in_location_id` integer NULL, `last_out_location_id` integer NULL, `shift_id` integer NULL);
--
-- Create model AttendanceSession
--
CREATE TABLE `attv2_session` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `attendance_date` date NOT NULL, `sequence` smallint UNSIGNED NOT NULL CHECK (`sequence` >= 0), `check_in` datetime(6) NULL, `check_out` datetime(6) NULL, `duration_minutes` integer NOT NULL, `status` varchar(20) NOT NULL, `check_in_event_id` integer NULL, `check_in_location_id` integer NULL, `check_out_event_id` integer NULL, `check_out_location_id` integer NULL, `company_id` integer NOT NULL, `employee_id` integer NOT NULL, `daily_id` integer NOT NULL);
--
-- Create model AttendanceAuditLog
--
CREATE TABLE `attv2_audit_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `entity_type` varchar(40) NOT NULL, `entity_id` integer NULL, `action` varchar(40) NOT NULL, `old_values` json NULL, `new_values` json NULL, `remarks` varchar(500) NULL, `changed_by` integer NULL, `changed_at` datetime(6) NOT NULL, `company_id` integer NOT NULL);
--
-- Alter unique_together for attendancedevice (1 constraint(s))
--
ALTER TABLE `attv2_device` ADD CONSTRAINT `attv2_device_company_id_code_a43356f2_uniq` UNIQUE (`company_id`, `code`);
--
-- Create index attv2_event_emp_time on field(s) company, employee, event_time of model attendanceevent
--
CREATE INDEX `attv2_event_emp_time` ON `attv2_event` (`company_id`, `employee_id`, `event_time`);
--
-- Create index attv2_event_emp_date on field(s) company, employee, attendance_date of model attendanceevent
--
CREATE INDEX `attv2_event_emp_date` ON `attv2_event` (`company_id`, `employee_id`, `attendance_date`);
--
-- Alter unique_together for attendanceshift (1 constraint(s))
--
ALTER TABLE `attv2_shift` ADD CONSTRAINT `attv2_shift_company_id_code_4b8a3b86_uniq` UNIQUE (`company_id`, `code`);
--
-- Create index attv2_assign_scope_from on field(s) company, scope, effective_from of model attendanceshiftassignment
--
CREATE INDEX `attv2_assign_scope_from` ON `attv2_shift_assignment` (`company_id`, `scope`, `effective_from`);
--
-- Create index attv2_assign_emp_from on field(s) employee, effective_from of model attendanceshiftassignment
--
CREATE INDEX `attv2_assign_emp_from` ON `attv2_shift_assignment` (`employee_id`, `effective_from`);
--
-- Alter unique_together for attendanceshiftschedule (1 constraint(s))
--
ALTER TABLE `attv2_shift_schedule` ADD CONSTRAINT `attv2_shift_schedule_shift_id_weekday_7a4912d3_uniq` UNIQUE (`shift_id`, `weekday`);
--
-- Create index attv2_sync_company_started on field(s) company, started_at of model attendancesynclog
--
CREATE INDEX `attv2_sync_company_started` ON `attv2_sync_log` (`company_id`, `started_at`);
--
-- Create index attv2_sync_collector_started on field(s) collector, started_at of model attendancesynclog
--
CREATE INDEX `attv2_sync_collector_started` ON `attv2_sync_log` (`collector_id`, `started_at`);
--
-- Create index attv2_raw_company_time on field(s) company, punch_time of model attendancerawpunch
--
CREATE INDEX `attv2_raw_company_time` ON `attv2_raw_punch` (`company_id`, `punch_time`);
--
-- Create index attv2_raw_company_status on field(s) company, status of model attendancerawpunch
--
CREATE INDEX `attv2_raw_company_status` ON `attv2_raw_punch` (`company_id`, `status`);
--
-- Create index attv2_raw_employee_time on field(s) employee, punch_time of model attendancerawpunch
--
CREATE INDEX `attv2_raw_employee_time` ON `attv2_raw_punch` (`employee_id`, `punch_time`);
--
-- Alter unique_together for attendancerawpunch (1 constraint(s))
--
ALTER TABLE `attv2_raw_punch` ADD CONSTRAINT `attv2_raw_punch_device_id_external_punch_id_a2a09401_uniq` UNIQUE (`device_id`, `external_punch_id`);
--
-- Create index attv2_daily_date_status on field(s) company, attendance_date, status of model employeedailyattendance
--
CREATE INDEX `attv2_daily_date_status` ON `attv2_daily_attendance` (`company_id`, `attendance_date`, `status`);
--
-- Alter unique_together for employeedailyattendance (1 constraint(s))
--
ALTER TABLE `attv2_daily_attendance` ADD CONSTRAINT `attv2_daily_attendance_company_id_employee_id_a_c2ae055b_uniq` UNIQUE (`company_id`, `employee_id`, `attendance_date`);
--
-- Create index attv2_session_emp_date on field(s) company, employee, attendance_date of model attendancesession
--
CREATE INDEX `attv2_session_emp_date` ON `attv2_session` (`company_id`, `employee_id`, `attendance_date`);
ALTER TABLE `attv2_device` ADD CONSTRAINT `attv2_device_company_id_93e575b9_fk_platform_company_id` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
ALTER TABLE `attv2_collector` ADD CONSTRAINT `attv2_collector_company_id_f6229be4_fk_platform_company_id` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
ALTER TABLE `attv2_collector_devices` ADD CONSTRAINT `attv2_collector_devices_attendancecollector_id_a_db0369be_uniq` UNIQUE (`attendancecollector_id`, `attendancedevice_id`);
ALTER TABLE `attv2_collector_devices` ADD CONSTRAINT `attv2_collector_devi_attendancecollector__84c77e4e_fk_attv2_col` FOREIGN KEY (`attendancecollector_id`) REFERENCES `attv2_collector` (`id`);
ALTER TABLE `attv2_collector_devices` ADD CONSTRAINT `attv2_collector_devi_attendancedevice_id_719e058d_fk_attv2_dev` FOREIGN KEY (`attendancedevice_id`) REFERENCES `attv2_device` (`id`);
ALTER TABLE `attv2_location` ADD CONSTRAINT `attv2_location_company_id_code_6e943410_uniq` UNIQUE (`company_id`, `code`);
ALTER TABLE `attv2_location` ADD CONSTRAINT `attv2_location_branch_id_a8c6ff10_fk_platform_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `platform_branch` (`id`);
ALTER TABLE `attv2_location` ADD CONSTRAINT `attv2_location_company_id_b1e017d3_fk_platform_company_id` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
ALTER TABLE `attv2_location` ADD CONSTRAINT `attv2_location_parent_id_f8654fac_fk_attv2_location_id` FOREIGN KEY (`parent_id`) REFERENCES `attv2_location` (`id`);
ALTER TABLE `attv2_raw_punch` ADD CONSTRAINT `attv2_raw_punch_collector_id_7dd7b24a_fk_attv2_collector_id` FOREIGN KEY (`collector_id`) REFERENCES `attv2_collector` (`id`);
ALTER TABLE `attv2_raw_punch` ADD CONSTRAINT `attv2_raw_punch_company_id_f97f950d_fk_platform_company_id` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
ALTER TABLE `attv2_raw_punch` ADD CONSTRAINT `attv2_raw_punch_device_id_3bcc784d_fk_attv2_device_id` FOREIGN KEY (`device_id`) REFERENCES `attv2_device` (`id`);
ALTER TABLE `attv2_raw_punch` ADD CONSTRAINT `attv2_raw_punch_employee_id_b6508b97_fk_auth_user_id` FOREIGN KEY (`employee_id`) REFERENCES `auth_user` (`id`);
ALTER TABLE `attv2_raw_punch` ADD CONSTRAINT `attv2_raw_punch_location_id_8afb24b8_fk_attv2_location_id` FOREIGN KEY (`location_id`) REFERENCES `attv2_location` (`id`);
ALTER TABLE `attv2_event` ADD CONSTRAINT `attv2_event_company_id_60f327ec_fk_platform_company_id` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
ALTER TABLE `attv2_event` ADD CONSTRAINT `attv2_event_device_id_a9cef070_fk_attv2_device_id` FOREIGN KEY (`device_id`) REFERENCES `attv2_device` (`id`);
ALTER TABLE `attv2_event` ADD CONSTRAINT `attv2_event_employee_id_ce90e770_fk_auth_user_id` FOREIGN KEY (`employee_id`) REFERENCES `auth_user` (`id`);
ALTER TABLE `attv2_event` ADD CONSTRAINT `attv2_event_location_id_3e3346a0_fk_attv2_location_id` FOREIGN KEY (`location_id`) REFERENCES `attv2_location` (`id`);
ALTER TABLE `attv2_event` ADD CONSTRAINT `attv2_event_raw_punch_id_79e9e51b_fk_attv2_raw_punch_id` FOREIGN KEY (`raw_punch_id`) REFERENCES `attv2_raw_punch` (`id`);
ALTER TABLE `attv2_settings` ADD CONSTRAINT `attv2_settings_company_id_042fd935_fk_platform_company_id` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
ALTER TABLE `attv2_shift` ADD CONSTRAINT `attv2_shift_company_id_2d91793f_fk_platform_company_id` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
ALTER TABLE `attv2_shift_assignment` ADD CONSTRAINT `attv2_shift_assignment_branch_id_89c7cef3_fk_platform_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `platform_branch` (`id`);
ALTER TABLE `attv2_shift_assignment` ADD CONSTRAINT `attv2_shift_assignme_company_id_7c261f14_fk_platform_` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
ALTER TABLE `attv2_shift_assignment` ADD CONSTRAINT `attv2_shift_assignment_employee_id_aa4f479c_fk_auth_user_id` FOREIGN KEY (`employee_id`) REFERENCES `auth_user` (`id`);
ALTER TABLE `attv2_shift_assignment` ADD CONSTRAINT `attv2_shift_assignment_shift_id_2e6538e4_fk_attv2_shift_id` FOREIGN KEY (`shift_id`) REFERENCES `attv2_shift` (`id`);
ALTER TABLE `attv2_shift_assignment` ADD CONSTRAINT `attv2_shift_assignment_team_lead_id_9b755f68_fk_auth_user_id` FOREIGN KEY (`team_lead_id`) REFERENCES `auth_user` (`id`);
ALTER TABLE `attv2_shift_schedule` ADD CONSTRAINT `attv2_shift_schedule_shift_id_b13c7c62_fk_attv2_shift_id` FOREIGN KEY (`shift_id`) REFERENCES `attv2_shift` (`id`);
ALTER TABLE `attv2_sync_log` ADD CONSTRAINT `attv2_sync_log_collector_id_14dc8527_fk_attv2_collector_id` FOREIGN KEY (`collector_id`) REFERENCES `attv2_collector` (`id`);
ALTER TABLE `attv2_sync_log` ADD CONSTRAINT `attv2_sync_log_company_id_82d7221a_fk_platform_company_id` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
ALTER TABLE `attv2_sync_log` ADD CONSTRAINT `attv2_sync_log_device_id_f9fbd7aa_fk_attv2_device_id` FOREIGN KEY (`device_id`) REFERENCES `attv2_device` (`id`);
ALTER TABLE `attv2_daily_attendance` ADD CONSTRAINT `attv2_daily_attendan_company_id_24732b78_fk_platform_` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
ALTER TABLE `attv2_daily_attendance` ADD CONSTRAINT `attv2_daily_attendance_employee_id_ba6ec125_fk_auth_user_id` FOREIGN KEY (`employee_id`) REFERENCES `auth_user` (`id`);
ALTER TABLE `attv2_daily_attendance` ADD CONSTRAINT `attv2_daily_attendan_first_in_location_id_2035ce49_fk_attv2_loc` FOREIGN KEY (`first_in_location_id`) REFERENCES `attv2_location` (`id`);
ALTER TABLE `attv2_daily_attendance` ADD CONSTRAINT `attv2_daily_attendan_last_out_location_id_9669f9ba_fk_attv2_loc` FOREIGN KEY (`last_out_location_id`) REFERENCES `attv2_location` (`id`);
ALTER TABLE `attv2_daily_attendance` ADD CONSTRAINT `attv2_daily_attendance_shift_id_b17e858b_fk_attv2_shift_id` FOREIGN KEY (`shift_id`) REFERENCES `attv2_shift` (`id`);
ALTER TABLE `attv2_session` ADD CONSTRAINT `attv2_session_check_in_event_id_b9fcab34_fk_attv2_event_id` FOREIGN KEY (`check_in_event_id`) REFERENCES `attv2_event` (`id`);
ALTER TABLE `attv2_session` ADD CONSTRAINT `attv2_session_check_in_location_id_293043b9_fk_attv2_location_id` FOREIGN KEY (`check_in_location_id`) REFERENCES `attv2_location` (`id`);
ALTER TABLE `attv2_session` ADD CONSTRAINT `attv2_session_check_out_event_id_2fae9420_fk_attv2_event_id` FOREIGN KEY (`check_out_event_id`) REFERENCES `attv2_event` (`id`);
ALTER TABLE `attv2_session` ADD CONSTRAINT `attv2_session_check_out_location_i_ae23c443_fk_attv2_loc` FOREIGN KEY (`check_out_location_id`) REFERENCES `attv2_location` (`id`);
ALTER TABLE `attv2_session` ADD CONSTRAINT `attv2_session_company_id_95ed88b7_fk_platform_company_id` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
ALTER TABLE `attv2_session` ADD CONSTRAINT `attv2_session_employee_id_46acb224_fk_auth_user_id` FOREIGN KEY (`employee_id`) REFERENCES `auth_user` (`id`);
ALTER TABLE `attv2_session` ADD CONSTRAINT `attv2_session_daily_id_82660569_fk_attv2_daily_attendance_id` FOREIGN KEY (`daily_id`) REFERENCES `attv2_daily_attendance` (`id`);
ALTER TABLE `attv2_audit_log` ADD CONSTRAINT `attv2_audit_log_company_id_0e3ad385_fk_platform_company_id` FOREIGN KEY (`company_id`) REFERENCES `platform_company` (`id`);
CREATE INDEX `attv2_audit_entity` ON `attv2_audit_log` (`company_id`, `entity_type`, `entity_id`);
CREATE INDEX `attv2_audit_changed` ON `attv2_audit_log` (`company_id`, `changed_at`);

-- -----------------------------------------------------------------------------
-- 2. New capabilities (platform_capability rows, no schema change)
--    Viewing other employees' V2 attendance reuses the existing
--    attendance.view_all / attendance.view_team capabilities.
-- -----------------------------------------------------------------------------
INSERT IGNORE INTO `platform_capability` (`code`, `module`, `description`) VALUES
  ('attendance.manage_devices', 'attendance', 'Manage attendance locations, devices and collectors; view raw punches and sync logs'),
  ('attendance.manage_shifts',  'attendance', 'Manage shifts, weekly schedules, shift assignments and attendance rules'),
  ('attendance.correct',        'attendance', 'Add or void attendance punches and recalculate attendance');

-- -----------------------------------------------------------------------------
-- 3. Role grants (DATA, adjust per environment)
--    Grants the new capabilities to the roles whose sample mapping in
--    create_memberships_from_groups.py already has '*' or 'attendance.*'
--    (applied on the dev DB on 2026-09-28). Review role names for each
--    environment before running; these are sample mappings, not a confirmed
--    business design. Manager is included only because its sample mapping
--    has 'attendance.*' - remove it if Managers should not manage devices.
-- -----------------------------------------------------------------------------
INSERT INTO `platform_role_capabilities` (`role_id`, `capability_id`)
SELECT r.`id`, c.`code`
  FROM `platform_role` r
  JOIN `platform_company` co ON co.`id` = r.`company_id`
  JOIN `platform_capability` c
    ON c.`code` IN ('attendance.manage_devices', 'attendance.manage_shifts', 'attendance.correct')
 WHERE (co.`short_name`, r.`name`) IN (('Digital Mesh', 'Director'), ('Digital Mesh', 'HR'),
                                        ('Digital Mesh', 'Manager'), ('EM Soft', 'CEO'),
                                        ('EM Soft', 'HR Manager'))
   AND NOT EXISTS (SELECT 1 FROM `platform_role_capabilities` x
                    WHERE x.`role_id` = r.`id` AND x.`capability_id` = c.`code`);

-- -----------------------------------------------------------------------------
-- 4. Only when this script is used INSTEAD of `manage.py migrate`:
--    record the migrations as applied.
-- -----------------------------------------------------------------------------
INSERT INTO `django_migrations` (`app`, `name`, `applied`)
SELECT 'platform_access', '0014_seed_attendance_v2_capabilities', NOW(6) FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM `django_migrations`
                    WHERE `app` = 'platform_access' AND `name` = '0014_seed_attendance_v2_capabilities');
INSERT INTO `django_migrations` (`app`, `name`, `applied`)
SELECT 'attendance_v2_access', '0001_initial', NOW(6) FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM `django_migrations`
                    WHERE `app` = 'attendance_v2_access' AND `name` = '0001_initial');
