# Generated by Django 5.2.9 on 2026-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_access", "0003_seed_capabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="legacy_company_id",
            field=models.IntegerField(
                blank=True,
                help_text="Bridges to the pre-existing settings.COMPANY/ORGANIZATION integer id (user_profile.company_id) during the module-by-module rollout.",
                null=True,
                unique=True,
            ),
        ),
    ]
