# Generated by Django 5.2.9 on 2026-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_access", "0005_add_leave_manage_all_capability"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="extra_capabilities",
            field=models.ManyToManyField(
                blank=True,
                db_table="platform_membership_extra_capabilities",
                related_name="extra_on_memberships",
                to="platform_access.capability",
            ),
        ),
    ]
