# Generated by Django 5.2.9 on 2026-09-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_access", "0007_seed_extended_capability_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires",
                    models.ManyToManyField(
                        blank=True,
                        db_table="platform_module_requires",
                        related_name="required_by",
                        to="platform_access.module",
                    ),
                ),
            ],
            options={
                "db_table": "platform_module",
            },
        ),
        migrations.CreateModel(
            name="CompanyModule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_modules",
                        to="platform_access.company",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_modules",
                        to="platform_access.module",
                    ),
                ),
            ],
            options={
                "db_table": "platform_company_module",
                "unique_together": {("company", "module")},
            },
        ),
    ]
