# Generated by Django 5.2.9 on 2026-10-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_access', '0014_seed_attendance_v2_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='leave_sandwich_rule',
            field=models.BooleanField(default=False),
        ),
    ]
