"""
Django settings for pTracker project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from datetime import datetime, timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

load_dotenv(os.path.join(os.path.dirname(BASE_DIR), ".env"))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =  str(os.getenv('SECRET_KEY'))
#tun%rdx%h+d5h3gbqlosgmv!s0+8lw#pwuc1&&7kq+34v8+f0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

REST_AUTH = {
    'USE_JWT': True,
    'OLD_PASSWORD_FIELD_ENABLED': True,
    'LOGOUT_ON_PASSWORD_CHANGE': False,
}

CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'dj_rest_auth',
    'rest_framework.authtoken',
    #'djangorestframework-jwt',
    'pTracker.dataaccess',
    'pTracker.admin_panel',
    'pTracker.api.projects',
    'pTracker.api.timesheet',
    'corsheaders',
    'pTracker.dataaccess.ptracker_access',
    'pTracker.wiki.sites',
    'pTracker.wiki.data_access.wiki_models',
    'widget_tweaks',


]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pTracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/wiki/sites/templates/', BASE_DIR + '/email_templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pTracker.wiki.sites.context_processors.user_group'
            ],
        },
    },
]


WSGI_APPLICATION = 'pTracker.wsgi.application'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

CELERY_ENABLE_UTC = False

CELERY_TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False




try:
    from pTracker.celery_config import *
except ImportError:
    raise

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        #'rest_framework.authentication.SessionAuthentication',
        #'rest_framework.authentication.BasicAuthentication',
    ),

    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],

    'EXCEPTION_HANDLER': ("pTracker.common.exception_handler.custom_rest_exception_handler")
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=14400),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('JWT',),
    'SIGNING_KEY': SECRET_KEY,
}

#send emails

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_SSL=False

ATT_DEVICE = {}

ATT_DEVICE['DM_IN'] = {
    'SerialNumber':str(os.getenv('DM_IN_SerialNumber')),
    'IpAddress': str(os.getenv('DM_IN_IpAddress')),
    'DeviceDirection':'IN'
}

ATT_DEVICE['DM_OUT'] = {
    'SerialNumber':str(os.getenv('DM_OUT_SerialNumber')),
    'IpAddress': str(os.getenv('DM_OUT_IpAddress')),
    'DeviceDirection': 'OUT'
}

ATT_DEVICE['EM_IN'] = {
    'SerialNumber': str(os.getenv('EM_IN_SerialNumber')),
    'IpAddress':str(os.getenv('EM_IN_IpAddress')),
    'DeviceDirection': 'IN'
}

ATT_DEVICE['EM_OUT'] = {
    'SerialNumber': str(os.getenv('EM_OUT_SerialNumber')),
    'IpAddress': str(os.getenv('EM_OUT_IpAddress')),
    'DeviceDirection': 'OUT'
}

EMAIL_ADDRESS={
    'donotreply':{
        'name': str(os.getenv('EMAIL_ADDRESS_donotreply_email')),
        'mailID': str(os.getenv('EMAIL_ADDRESS_donotreply_email')),
        'password': str(os.getenv('EMAIL_ADDRESS_donotreply_password'))
    },
    'do_not_reply':{
        'name': str(os.getenv('EMAIL_ADDRESS_do_not_reply_email')),
        'mailID': str(os.getenv('EMAIL_ADDRESS_do_not_reply_email')),
        'password': str(os.getenv('EMAIL_ADDRESS_do_not_reply_password'))
    },
    'account_dm':{
        'name': str(os.getenv('EMAIL_ACCOUNT_DM')),
        'mailID': str(os.getenv('EMAIL_ACCOUNT_DM')),
        'password': str(os.getenv('EMAIL_ACCOUNT_DM_PASSWORD'))
    },
    'account_em':{
        'name': str(os.getenv('EMAIL_ACCOUNT_EM')),
        'mailID': str(os.getenv('EMAIL_ACCOUNT_EM')),
        'password': str(os.getenv('EMAIL_ACCOUNT_EM_PASSWORD'))
    }
}

FILE_UPLOAD_MODE = "LOCAL"
AWS_ACCESS_KEY_ID = str(os.getenv('AWS_ACCESS_KEY_ID'))
AWS_SECRET_ACCESS_KEY = str(os.getenv('AWS_SECRET_ACCESS_KEY'))
AWS_S3_REGION_NAME = str(os.getenv('AWS_S3_REGION_NAME'))
AWS_STORAGE_BUCKET_NAME = str(os.getenv('AWS_STORAGE_BUCKET_NAME'))

from .constants import *
