# Generated by Django 5.2.9 on 2026-09-28 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("platform_access", "0014_seed_attendance_v2_capabilities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("essl", "eSSL"),
                            ("zkteco", "ZKTeco"),
                            ("other_biometric", "Other biometric"),
                            ("web", "Web check-in"),
                            ("mobile", "Mobile check-in"),
                            ("api", "API integration"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("requires_wfh_approval", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_devices",
                        to="platform_access.company",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_device",
            },
        ),
        migrations.CreateModel(
            name="AttendanceCollector",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collector_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "collector_type",
                    models.CharField(
                        choices=[
                            ("essl", "eSSL"),
                            ("zkteco", "ZKTeco"),
                            ("other_biometric", "Other biometric"),
                            ("web", "Web check-in"),
                            ("mobile", "Mobile check-in"),
                            ("api", "API integration"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("api_key_hash", models.CharField(max_length=64)),
                ("api_key_prefix", models.CharField(max_length=12)),
                ("key_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reported_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500, null=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_collectors",
                        to="platform_access.company",
                    ),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        blank=True,
                        db_table="attv2_collector_devices",
                        related_name="collectors",
                        to="attendance_v2_access.attendancedevice",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_collector",
            },
        ),
        migrations.CreateModel(
            name="AttendanceLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("building", "Building"),
                            ("floor", "Floor"),
                            ("area", "Area"),
                            ("room", "Room"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_locations",
                        to="platform_access.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_locations",
                        to="platform_access.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="attendance_v2_access.attendancelocation",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_location",
                "unique_together": {("company", "code")},
            },
        ),
        migrations.AddField(
            model_name="attendancedevice",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="attendance_v2_access.attendancelocation",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceRawPunch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_employee_id", models.CharField(max_length=64)),
                ("external_punch_id", models.CharField(max_length=128)),
                ("punch_time", models.DateTimeField()),
                (
                    "raw_punch_type",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "punch_type",
                    models.CharField(
                        choices=[
                            ("IN", "In"),
                            ("OUT", "Out"),
                            ("UNSPECIFIED", "Unspecified"),
                        ],
                        default="UNSPECIFIED",
                        max_length=12,
                    ),
                ),
                ("source", models.CharField(max_length=20)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("received_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("unresolved_employee", "Employee not identified"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_punches",
                        to="attendance_v2_access.attendancecollector",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_raw_punches",
                        to="platform_access.company",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_punches",
                        to="attendance_v2_access.attendancedevice",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_v2_raw_punches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_punches",
                        to="attendance_v2_access.attendancelocation",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_raw_punch",
            },
        ),
        migrations.CreateModel(
            name="AttendanceEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("IN", "In"),
                            ("OUT", "Out"),
                            ("UNSPECIFIED", "Unspecified"),
                        ],
                        default="UNSPECIFIED",
                        max_length=12,
                    ),
                ),
                ("attendance_date", models.DateField(blank=True, null=True)),
                ("source", models.CharField(max_length=20)),
                ("is_manual", models.BooleanField(default=False)),
                (
                    "manual_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("void", "Void")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "void_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("voided_by", models.IntegerField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_events",
                        to="platform_access.company",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="attendance_v2_access.attendancedevice",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_v2_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="attendance_v2_access.attendancelocation",
                    ),
                ),
                (
                    "raw_punch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event",
                        to="attendance_v2_access.attendancerawpunch",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_event",
            },
        ),
        migrations.CreateModel(
            name="AttendanceSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duplicate_punch_window_minutes",
                    models.PositiveIntegerField(default=2),
                ),
                (
                    "unspecified_punch_mode",
                    models.CharField(
                        choices=[
                            ("alternate", "Alternate IN / OUT"),
                            ("first_last", "First punch IN, last punch OUT"),
                        ],
                        default="alternate",
                        max_length=20,
                    ),
                ),
                (
                    "collector_offline_after_minutes",
                    models.PositiveIntegerField(default=15),
                ),
                ("use_holiday_calendar", models.BooleanField(default=True)),
                ("use_leave_records", models.BooleanField(default=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_settings",
                        to="platform_access.company",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_settings",
            },
        ),
        migrations.CreateModel(
            name="AttendanceShift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=30)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("expected_work_minutes", models.PositiveIntegerField()),
                ("grace_in_minutes", models.PositiveIntegerField(default=0)),
                ("grace_out_minutes", models.PositiveIntegerField(default=0)),
                ("break_minutes", models.PositiveIntegerField(default=0)),
                ("break_start", models.TimeField(blank=True, null=True)),
                ("break_end", models.TimeField(blank=True, null=True)),
                ("is_flexible", models.BooleanField(default=False)),
                (
                    "min_present_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "half_day_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("overtime_enabled", models.BooleanField(default=False)),
                (
                    "overtime_basis",
                    models.CharField(
                        choices=[
                            ("after_shift_end", "Time worked after shift end"),
                            (
                                "beyond_expected",
                                "Work minutes beyond expected work minutes",
                            ),
                        ],
                        default="after_shift_end",
                        max_length=20,
                    ),
                ),
                ("min_overtime_minutes", models.PositiveIntegerField(default=0)),
                (
                    "checkin_window_before_minutes",
                    models.PositiveIntegerField(default=240),
                ),
                (
                    "checkout_window_after_minutes",
                    models.PositiveIntegerField(default=480),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_shifts",
                        to="platform_access.company",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_shift",
            },
        ),
        migrations.CreateModel(
            name="AttendanceShiftAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("team", "Team (reporting lead)"),
                            ("branch", "Branch"),
                            ("company", "Company default"),
                        ],
                        max_length=20,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.CharField(blank=True, max_length=500, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_shift_assignments",
                        to="platform_access.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_shift_assignments",
                        to="platform_access.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="attendance_v2_access.attendanceshift",
                    ),
                ),
                (
                    "team_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_team_shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attv2_shift_assignment",
            },
        ),
        migrations.CreateModel(
            name="AttendanceShiftSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("is_working_day", models.BooleanField(default=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "expected_work_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="attendance_v2_access.attendanceshift",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_shift_schedule",
            },
        ),
        migrations.CreateModel(
            name="AttendanceSyncLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("punches", "Punch batch"),
                            ("heartbeat", "Heartbeat"),
                        ],
                        default="punches",
                        max_length=20,
                    ),
                ),
                ("request_id", models.CharField(max_length=64)),
                ("remote_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("received_count", models.IntegerField(default=0)),
                ("accepted_count", models.IntegerField(default=0)),
                ("duplicate_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, null=True)),
                ("message", models.CharField(blank=True, max_length=500, null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="attendance_v2_access.attendancecollector",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_sync_logs",
                        to="platform_access.company",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="attendance_v2_access.attendancedevice",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_sync_log",
            },
        ),
        migrations.AddField(
            model_name="attendancerawpunch",
            name="sync_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raw_punches",
                to="attendance_v2_access.attendancesynclog",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeDailyAttendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                ("shift_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("working", "Working day"),
                            ("weekly_off", "Weekly off"),
                            ("holiday", "Holiday"),
                        ],
                        default="working",
                        max_length=20,
                    ),
                ),
                (
                    "leave_portion",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("full", "Full day"),
                            ("half", "Half day"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("half_day", "Half day"),
                            ("absent", "Absent"),
                            ("leave", "Leave"),
                            ("holiday", "Holiday"),
                            ("weekly_off", "Weekly off"),
                            ("incomplete", "Incomplete (missing punch)"),
                            ("not_started", "Not started"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_in", models.DateTimeField(blank=True, null=True)),
                ("last_out", models.DateTimeField(blank=True, null=True)),
                ("total_work_minutes", models.IntegerField(default=0)),
                ("total_break_minutes", models.IntegerField(default=0)),
                ("expected_work_minutes", models.IntegerField(default=0)),
                ("late_minutes", models.IntegerField(default=0)),
                ("early_departure_minutes", models.IntegerField(default=0)),
                ("overtime_minutes", models.IntegerField(default=0)),
                ("is_late", models.BooleanField(default=False)),
                ("is_early_departure", models.BooleanField(default=False)),
                ("session_count", models.IntegerField(default=0)),
                ("has_missing_punch", models.BooleanField(default=False)),
                ("remarks", models.CharField(blank=True, max_length=500, null=True)),
                ("processed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_daily",
                        to="platform_access.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_v2_daily",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "first_in_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="attendance_v2_access.attendancelocation",
                    ),
                ),
                (
                    "last_out_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="attendance_v2_access.attendancelocation",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_attendance",
                        to="attendance_v2_access.attendanceshift",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_daily_attendance",
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                ("sequence", models.PositiveSmallIntegerField()),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("missing_out", "Missing OUT"),
                            ("missing_in", "Missing IN"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "check_in_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="attendance_v2_access.attendanceevent",
                    ),
                ),
                (
                    "check_in_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="attendance_v2_access.attendancelocation",
                    ),
                ),
                (
                    "check_out_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="attendance_v2_access.attendanceevent",
                    ),
                ),
                (
                    "check_out_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="attendance_v2_access.attendancelocation",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_sessions",
                        to="platform_access.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_v2_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "daily",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="attendance_v2_access.employeedailyattendance",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_session",
            },
        ),
        migrations.CreateModel(
            name="AttendanceAuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=40)),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                ("action", models.CharField(max_length=40)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("remarks", models.CharField(blank=True, max_length=500, null=True)),
                ("changed_by", models.IntegerField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_audit_logs",
                        to="platform_access.company",
                    ),
                ),
            ],
            options={
                "db_table": "attv2_audit_log",
                "indexes": [
                    models.Index(
                        fields=["company", "entity_type", "entity_id"],
                        name="attv2_audit_entity",
                    ),
                    models.Index(
                        fields=["company", "changed_at"], name="attv2_audit_changed"
                    ),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="attendancedevice",
            unique_together={("company", "code")},
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["company", "employee", "event_time"],
                name="attv2_event_emp_time",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["company", "employee", "attendance_date"],
                name="attv2_event_emp_date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendanceshift",
            unique_together={("company", "code")},
        ),
        migrations.AddIndex(
            model_name="attendanceshiftassignment",
            index=models.Index(
                fields=["company", "scope", "effective_from"],
                name="attv2_assign_scope_from",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceshiftassignment",
            index=models.Index(
                fields=["employee", "effective_from"], name="attv2_assign_emp_from"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendanceshiftschedule",
            unique_together={("shift", "weekday")},
        ),
        migrations.AddIndex(
            model_name="attendancesynclog",
            index=models.Index(
                fields=["company", "started_at"], name="attv2_sync_company_started"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesynclog",
            index=models.Index(
                fields=["collector", "started_at"], name="attv2_sync_collector_started"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerawpunch",
            index=models.Index(
                fields=["company", "punch_time"], name="attv2_raw_company_time"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerawpunch",
            index=models.Index(
                fields=["company", "status"], name="attv2_raw_company_status"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerawpunch",
            index=models.Index(
                fields=["employee", "punch_time"], name="attv2_raw_employee_time"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerawpunch",
            unique_together={("device", "external_punch_id")},
        ),
        migrations.AddIndex(
            model_name="employeedailyattendance",
            index=models.Index(
                fields=["company", "attendance_date", "status"],
                name="attv2_daily_date_status",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeedailyattendance",
            unique_together={("company", "employee", "attendance_date")},
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["company", "employee", "attendance_date"],
                name="attv2_session_emp_date",
            ),
        ),
    ]
